### ISSUE TITLE
Is there a circuit drawing?

### ISSUE THREAD

**Issue by khoroshyy** [raacampbell/openstage#15]
Hi.
Is there a circuit drawing?
Best.
Petro.

**Comment by raacampbell** [comment]
There are PCB files here: https://github.com/raacampbell/openstage/tree/master/OpenStage_PCB
There should be sufficient information on the wiring in the manuscript. Others have built based on that with no additional input.

**Comment by khoroshyy** [comment]
Thanks for pointing out,
I somehow missed the csh file but opened it in Kicad.
Best.
Petro.

**Comment by raacampbell** [comment]
Note that what's on GitHub now is a modified design, since some of the original parts no longer are available. I have not built the new design and I don't have the capacity to do so. I can help with general queries, though. The whole thing works surprisingly well, so if you are motivated you should be able to get it working.

**Comment by khoroshyy** [comment]
Thanks.
I am planning to reassign pins to use this board:
https://www.laskakit.cz/arduino-cnc-shield-v3/
Hopefully, it will be possible.
Best.
Petro.
